Adding all devDependencies to the Samples project to avoid errors like this:
EXEC : error : Command failed: pnpm compile [/home/runner/work/Orchard-Vue.js/Orchard-Vue.js/Lombiq.VueJs.Samples/Lombiq.VueJs.Samples.csproj]
  node:internal/modules/cjs/loader:1404
    throw err;
    ^

EXEC : error : Cannot find module '@rollup/plugin-json' [/home/runner/work/Orchard-Vue.js/Orchard-Vue.js/Lombiq.VueJs.Samples/Lombiq.VueJs.Samples.csproj]
  Require stack:
  - /home/runner/work/Orchard-Vue.js/Orchard-Vue.js/Lombiq.VueJs.Samples/node_modules/.lv/Assets/Scripts/helpers/vue-sfc-compiler-pipeline.js
      at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
      at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
      at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
      at Function._load (node:internal/modules/cjs/loader:1211:37)
      at TracingChannel.traceSync (node:diagnostics_channel:322:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
      at Module.require (node:internal/modules/cjs/loader:1487:12)
      at require (node:internal/modules/helpers:135:16)
      at Object.<anonymous> (/home/runner/work/Orchard-Vue.js/Orchard-Vue.js/Lombiq.VueJs.Samples/node_modules/.lv/Assets/Scripts/helpers/vue-sfc-compiler-pipeline.js:2:14)
      at Module._compile (node:internal/modules/cjs/loader:1730:14) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/home/runner/work/Orchard-Vue.js/Orchard-Vue.js/Lombiq.VueJs.Samples/node_modules/.lv/Assets/Scripts/helpers/vue-sfc-compiler-pipeline.js'
    ]
  }